export const CLINIC_INFO_REQUEST = 'CLINIC_INFO_REQUEST';
export const CLINIC_INFO_SUCCESS = 'CLINIC_INFO_SUCCESS';
export const CLINIC_INFO_FAIL = 'CLINIC_INFO_FAIL';

export const CLINIC_TIMESLOTS_REQUEST = 'CLINIC_TIMESLOTS_REQUEST';
export const CLINIC_TIMESLOTS_SUCCESS = 'CLINIC_TIMESLOTS_SUCCESS';
export const CLINIC_TIMESLOTS_FAIL = 'CLINIC_TIMESLOTS_FAIL';

export const CLINIC_CALENDAR_REQUEST = 'CLINIC_CALENDAR_REQUEST';
export const CLINIC_CALENDAR_SUCCESS = 'CLINIC_CALENDAR_SUCCESS';
export const CLINIC_CALENDAR_FAIL = 'CLINIC_CALENDAR_FAIL';

export const DOCTOR_CALENDAR_REQUEST = 'DOCTOR_CALENDAR_REQUEST';
export const DOCTOR_CALENDAR_SUCCESS = 'DOCTOR_CALENDAR_SUCCESS';
export const DOCTOR_CALENDAR_FAIL = 'DOCTOR_CALENDAR_FAIL';

export const GET_CLINICS_REQUEST = 'GET_CLINICS_REQUEST';
export const GET_CLINICS_SUCCESS = 'GET_CLINICS_SUCCESS';
export const GET_CLINICS_FAIL = 'GET_CLINICS_FAIL';



export const CLINICS_PATIENTS_REQUEST = 'CLINICS_PATIENTS_REQUEST';
export const CLINICS_PATIENTS_SUCCESS = 'CLINICS_PATIENTS_SUCCESS';
export const CLINICS_PATIENTS_FAIL = 'CLINICS_PATIENTS_FAIL';

export const CLINICS_APPOINTMENTS_REQUEST = 'CLINICS_APPOINTMENTS_REQUEST';
export const CLINICS_APPOINTMENTS_SUCCESS = 'CLINICS_APPOINTMENTS_SUCCESS';
export const CLINICS_APPOINTMENTS_FAIL = 'CLINICS_APPOINTMENTS_FAIL';

export const CLINIC_DOCTORS_REQUEST = 'CLINIC_DOCTORS_REQUEST';
export const CLINIC_DOCTORS_SUCCESS = 'CLINIC_DOCTORS_SUCCESS';
export const CLINIC_DOCTORS_FAIL = 'CLINIC_DOCTORS_FAIL';

export const CLINICS_APPROVED_APPOINTMENTS_REQUEST =
  'CLINICS_APPROVED_APPOINTMENTS_REQUEST';
export const CLINICS_APPROVED_APPOINTMENTS_SUCCESS =
  'CLINICS_APPROVED_APPOINTMENTS_SUCCESS';
export const CLINICS_APPROVED_APPOINTMENTS_FAIL =
  'CLINICS_APPROVED_APPOINTMENTS_FAIL';

