export const DOCTOR_APPROVED_APPOINTMENTS_REQUEST =
  'DOCTOR_APPROVED_APPOINTMENTS_REQUEST';
export const DOCTOR_APPROVED_APP_SUCCESS =
  'DOCTOR_APPROVED_APP_SUCCESS';
export const DOCTOR_APPROVED_APPOINTMENTS_FAIL =
  'DOCTOR_APPROVED_APPOINTMENTS_FAIL';
