export const PATIENT_INFO_REQUEST = 'PATIENT_INFO_REQUEST';
export const PATIENT_INFO_SUCCESS = 'PATIENT_INFO_SUCCESS';
export const PATIENT_INFO_FAIL = 'PATIENT_INFO_FAIL';

export const PATIENT_REQUEST_CLINICS = 'PATIENT_REQUEST_CLINICS';
export const PATIENT_SUCCESS_CLINICS = 'PATIENT_SUCCESS_CLINICS';
export const PATIENT_FAIL_CLINICS = 'PATIENT_FAIL_CLINICS';

export const PATIENT_DOCTORS_CLINICS_AROUND_REQUEST =
  'PATIENT_DOCTORS_CLINICS_AROUND_REQUEST';
export const PATIENT_DOCTORS_CLINICS_AROUND_SUCCESS =
  'PATIENT_DOCTORS_CLINICS_AROUND_SUCCESS';
export const PATIENT_DOCTORS_CLINICS_AROUND_FAIL =
  'PATIENT_DOCTORS_CLINICS_AROUND_FAIL';

export const PATIENT_TIMESLOTS_REQUEST = 'PATIENT_TIMESLOTS_REQUEST';
export const PATIENT_TIMESLOTS_SUCCESS = 'PATIENT_TIMESLOTS_SUCCESS';
export const PATIENT_TIMESLOTS_FAIL = 'PATIENT_TIMESLOTS_FAIL';

export const PATIENT_CALENDAR_REQUEST = 'PATIENT_CALENDAR_REQUEST';
export const PATIENT_CALENDAR_SUCCESS = 'PATIENT_CALENDAR_SUCCESS';
export const PATIENT_CALENDAR_FAIL = 'PATIENT_CALENDAR_FAIL';

export const PATIENT_APPOINTMENTS_REQUEST = 'PATIENT_APPOINTMENTS_REQUEST';
export const PATIENT_APPOINTMENTS_SUCCESS = 'PATIENT_APPOINTMENTS_SUCCESS';
export const PATIENT_APPOINTMENTS_FAIL = 'PATIENT_APPOINTMENTS_FAIL';

export const PATIENT_CLINICS_REQUEST = 'PATIENT_CLINICS_REQUEST';
export const PATIENT_CLINICS_SUCCESS = 'PATIENT_CLINICS_SUCCESS';
export const PATIENT_CLINICS_FAIL = 'PATIENT_CLINICS_FAIL';

export const PATIENTS_FOR_REVIEWS_REQUEST = 'PATIENTS_FOR_REVIEWS_REQUEST';
export const PATIENTS_FOR_REVIEWS_SUCCESS = 'PATIENTS_FOR_REVIEWS_SUCCESS';
export const PATIENTS_FOR_REVIEWS_FAIL = 'PATIENTS_FOR_REVIEWS_FAIL';
