export const langObj = {
  en: {
    loginNowNoAccount: "Login without account",
    motivationalQuoteOfTheDay: "Motivational quote of the day",
    luckyColorOfTheDay: "Culoarea norocoasă a zilei",
    luckyHours: "Lucky Hours",
    motivationalQuotes: "Motivational Quotes",
    //AUTH
    firebaseErrorInvalidEmail: "The email address is invalid.",
    firebaseErrorEmailAlreadyInUse:
      "An account already exists with this email address.",
    firebaseErrorWeakPassword: "The password is too weak.",
    firebaseErrorUserNotFound: "No user found with this email address.",
    firebaseErrorUserDisabled: "This user has been disabled.",
    firebaseErrorWrongPassword: "Incorrect password. Please try again.",
    firebaseErrorTooManyRequests: "Too many requests. Please try again later.",
    firebaseErrorOperationNotAllowed:
      "Operation not allowed. Please contact support.",
    firebaseErrorNetworkRequestFailed:
      "Network error. Please check your internet connection.",
    firebaseErrorUnknown: "An unknown error occurred. Please try again.",
    //AUTH
    personalReading: "Personalized Reading",
    futureReading: "Future Reading",
    luckyNumber: "Lucky Number",
    luckyColor: "Lucky Color",
    touchToShuffle: "Touch to shuffle",
    helloUser: "Hello",
    //new
    login: "Login",
    email: "E-mail",
    password: "Password",
    forgotPassword: "Forgot Password",
    dntHaveAccount: "Don't have an account?",
    signUp: "Register",
    loginNow: "Login",
    alreadyAccount: "Already have an account?",
    registerLogin: "Sign in",
    register: "Register",
    myAccount: "My Account",
    currentPassword: "Current Password",
    createPassword: "New Password",
    confirmPassword: "Confirm Password",
    firstName: "First Name",
    lastName: "Last Name",
    changeEmail: "Change e-mail",
    changePassword: "Change password",
    changePhoneNumber: "Change phone number",
    deleteAccount: "Delete account",
    logOut: "Log Out",
    settings: "Settings",
    saveChanges: "Save changes",
    passDontMatch: "Passwords doesn't match",
    enterPasswordCurrent: "Enter Current Password",
    resetPassword: "Reset Password",
    backToLogin: "Back To Login",
    historyPersonalized: "History - personalized reading",
    historyFuture: "History - future reading",
    historyTypePersonalized: "Personalized reading",
    historyTypeFuture: "Future reading",
    welcomeTo: "Welcome To",
    tarotByAi: "Tarot by AI",
    onboardingFirstTitle: "Welcome To",
    onboardingFirstTitleMessage: "Tarot by AI",
    onboardingSecondTitle: "Tarot by AI",
    onboardingSecondTitleMessage: "Get personalized readings",
    onboardingThirdTitle: "Tarot by AI",
    onboardingThirdTitleMessage: "Get reading about your future",
    skip: "SKIP",
    nextOnboard: "NEXT",
    clinicLoginRedirect: "Continue",
  },
  ro: {
    loginNowNoAccount: "Autentificare fără cont",
    motivationalQuoteOfTheDay: "Citat motivațional al zilei",
    luckyColorOfTheDay: "Culoarea norocoasă a zilei",
    luckyHours: "Ore norocoase",
    motivationalQuotes: "Citate Motivationale",
    //AUTH
    firebaseErrorInvalidEmail: "Adresa de email introdusă este invalidă.",
    firebaseErrorEmailAlreadyInUse:
      "Există deja un cont asociat cu această adresă de email.",
    firebaseErrorWeakPassword: "Parola introdusă este prea slabă.",
    firebaseErrorUserNotFound:
      "Nu s-a găsit niciun utilizator cu această adresă de email.",
    firebaseErrorUserDisabled: "Acest utilizator a fost dezactivat.",
    firebaseErrorWrongPassword:
      "Parolă incorectă. Vă rugăm să încercați din nou.",
    firebaseErrorTooManyRequests:
      "Prea multe solicitări. Vă rugăm să încercați din nou mai târziu.",
    firebaseErrorOperationNotAllowed:
      "Operațiunea nu este permisă. Vă rugăm să contactați suportul.",
    firebaseErrorNetworkRequestFailed:
      "Eroare de rețea. Vă rugăm să verificați conexiunea la internet.",
    firebaseErrorUnknown:
      "A apărut o eroare necunoscută. Vă rugăm să încercați din nou.",
    //AUTH

    personalReading: "Citire personalizată",
    futureReading: "Citire de viitor",
    luckyNumber: "Numărul norocos",
    luckyColor: "Culoarea norocoasă",
    touchToShuffle: "Atinge pentru amestecare",
    helloUser: "Salut",
    //new
    login: "Autentificare",
    email: "E-mail",
    password: "Parolă",
    forgotPassword: "Ți-ai uitat parola?",
    dntHaveAccount: "Nu ai un cont?",
    signUp: "Înregistrare",
    loginNow: "Autentificare",
    alreadyAccount: "Ai deja un cont?",
    registerLogin: "Intră în cont",
    register: "Înregistrare",
    myAccount: "Contul Meu",
    currentPassword: "Parola Actuală",
    createPassword: "Parolă Nouă",
    confirmPassword: "Confirmă Parola",
    firstName: "Prenume",
    lastName: "Nume",
    changeEmail: "Schimbă e-mailul",
    changePassword: "Schimbă parola",
    changePhoneNumber: "Schimbă numărul de telefon",
    deleteAccount: "Șterge contul",
    logOut: "Deconectare",
    settings: "Setări",
    saveChanges: "Salvează Modificările",
    passDontMatch: "Parolele nu se potrivesc",
    enterPasswordCurrent: "Introdu Parola Actuală",
    resetPassword: "Resetează Parola",
    backToLogin: "Înapoi la Autentificare",
    historyPersonalized: "Istoric - lectură personalizată",
    historyFuture: "Istoric - lectură viitoare",
    historyTypePersonalized: "Lectură Personalizată",
    historyTypeFuture: "Lectură despre Viitor",
    welcomeTo: "Bun Venit la",
    tarotByAi: "Tarot prin AI",
    onboardingFirstTitle: "Bun Venit la",
    onboardingFirstTitleMessage: "Tarot prin AI",
    onboardingSecondTitle: "Tarot prin AI",
    onboardingSecondTitleMessage: "Obțineți lecturi personalizate",
    onboardingThirdTitle: "Tarot prin AI",
    onboardingThirdTitleMessage: "Obțineți lecturi despre viitorul tău",
    skip: "OMITE",
    nextOnboard: "URMĂTORUL",
    clinicLoginRedirect: "Continuă",
  },
  es: {
    loginNowNoAccount: "Iniciar sesión sin una cuenta",
    motivationalQuoteOfTheDay: "Frase motivacional del día",
    luckyColorOfTheDay: "Color de la suerte del día",
    luckyHours: "Horas de suerte",
    motivationalQuotes: "Citas Motivacionales",
    //AUTH
    firebaseErrorInvalidEmail:
      "La dirección de correo electrónico es inválida.",
    firebaseErrorEmailAlreadyInUse:
      "Ya existe una cuenta con esta dirección de correo electrónico.",
    firebaseErrorWeakPassword: "La contraseña es demasiado débil.",
    firebaseErrorUserNotFound:
      "No se encontró ningún usuario con esta dirección de correo electrónico.",
    firebaseErrorUserDisabled: "Este usuario ha sido deshabilitado.",
    firebaseErrorWrongPassword:
      "Contraseña incorrecta. Por favor, inténtalo de nuevo.",
    firebaseErrorTooManyRequests:
      "Demasiadas solicitudes. Por favor, inténtalo de nuevo más tarde.",
    firebaseErrorOperationNotAllowed:
      "Operación no permitida. Por favor, contacta con el soporte.",
    firebaseErrorNetworkRequestFailed:
      "Error de red. Por favor, verifica tu conexión a internet.",
    firebaseErrorUnknown:
      "Ocurrió un error desconocido. Por favor, inténtalo de nuevo.",
    //AUTH
    personalReading: "Lectura personalizada",
    futureReading: "Lectura del futuro",
    luckyNumber: "Número de la suerte",
    luckyColor: "Color de la suerte",
    touchToShuffle: "Toca para mezclar",
    helloUser: "Hola",
    //new
    login: "Autenticación",
    email: "Correo Electrónico",
    password: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    dntHaveAccount: "¿No tienes una cuenta?",
    signUp: "Regístrate",
    loginNow: "Inicia sesión",
    alreadyAccount: "¿Ya tienes una cuenta?",
    registerLogin: "Acceder a la cuenta",
    register: "Registro",
    myAccount: "Mi Cuenta",
    currentPassword: "Contraseña Actual",
    createPassword: "Nueva Contraseña",
    confirmPassword: "Confirma la Contraseña",
    firstName: "Nombre",
    lastName: "Apellido",
    changeEmail: "Cambiar correo electrónico",
    changePassword: "Cambiar contraseña",
    changePhoneNumber: "Cambiar número de teléfono",
    deleteAccount: "Eliminar cuenta",
    logOut: "Cerrar sesión",
    settings: "Ajustes",
    saveChanges: "Guardar Cambios",
    passDontMatch: "Las contraseñas no coinciden",
    enterPasswordCurrent: "Introduce la Contraseña Actual",
    resetPassword: "Restablecer Contraseña",
    backToLogin: "Volver a Iniciar Sesión",
    historyPersonalized: "Historial - lectura personalizada",
    historyFuture: "Historial - lectura futura",
    historyTypePersonalized: "Lectura Personalizada",
    historyTypeFuture: "Lectura sobre el Futuro",
    welcomeTo: "Bienvenido a",
    tarotByAi: "Tarot por AI",
    onboardingFirstTitle: "Bienvenido a",
    onboardingFirstTitleMessage: "Tarot por AI",
    onboardingSecondTitle: "Tarot por AI",
    onboardingSecondTitleMessage: "Obtén lecturas personalizadas",
    onboardingThirdTitle: "Tarot por AI",
    onboardingThirdTitleMessage: "Obtén lecturas sobre tu futuro",
    skip: "OMITIR",
    nextOnboard: "SIGUIENTE",
    clinicLoginRedirect: "Continuar",
  },
};
