export const langObj = {
  en: {
    history: "History",
    selectLanguage: "Select Language",
    firebaseErrorInvalidCredentials:
      "Invalid Credentials, email or password not good. If you think the e-mail is good try reseting the password",
    loginNowNoAccount: "Login without account",
    motivationalQuoteOfTheDay: "Motivational quote of the day",
    luckyColorOfTheDay: "Culoarea norocoasă a zilei",
    luckyHours: "Lucky Hours",
    motivationalQuotes: "Motivational Quotes",
    //AUTH
    firebaseErrorInvalidEmail: "The email address is invalid.",
    firebaseErrorEmailAlreadyInUse:
      "An account already exists with this email address.",
    firebaseErrorWeakPassword: "The password is too weak.",
    firebaseErrorUserNotFound: "No user found with this email address.",
    firebaseErrorUserDisabled: "This user has been disabled.",
    firebaseErrorWrongPassword: "Incorrect password. Please try again.",
    firebaseErrorTooManyRequests: "Too many requests. Please try again later.",
    firebaseErrorOperationNotAllowed:
      "Operation not allowed. Please contact support.",
    firebaseErrorNetworkRequestFailed:
      "Network error. Please check your internet connection.",
    firebaseErrorUnknown: "An unknown error occurred. Please try again.",
    //AUTH
    personalReading: "Personalized Reading",
    futureReading: "Future Reading",
    luckyNumber: "Lucky Number",
    luckyColor: "Lucky Color",
    touchToShuffle: "Touch to shuffle",
    helloUser: "Hello",
    //new
    login: "Login",
    email: "E-mail",
    password: "Password",
    forgotPassword: "Forgot Password",
    dntHaveAccount: "Don't have an account?",
    signUp: "Register",
    loginNow: "Login",
    alreadyAccount: "Already have an account?",
    registerLogin: "Sign in",
    register: "Register",
    myAccount: "My Account",
    currentPassword: "Current Password",
    createPassword: "New Password",
    confirmPassword: "Confirm Password",
    firstName: "First Name",
    lastName: "Last Name",
    changeEmail: "Change e-mail",
    changePassword: "Change password",
    changePhoneNumber: "Change phone number",
    deleteAccount: "Delete account",
    logOut: "Log Out",
    settings: "Settings",
    saveChanges: "Save changes",
    passDontMatch: "Passwords doesn't match",
    enterPasswordCurrent: "Enter Current Password",
    resetPassword: "Reset Password",
    backToLogin: "Back To Login",
    historyPersonalized: "History - personalized reading",
    historyFuture: "History - future reading",
    historyTypePersonalized: "Personalized reading",
    historyTypeFuture: "Future reading",
    welcomeTo: "Welcome To",
    tarotByAi: "Tarot by AI",
    onboardingFirstTitle: "Welcome To",
    onboardingFirstTitleMessage: "Tarot by AI",
    onboardingSecondTitle: "Tarot by AI",
    onboardingSecondTitleMessage: "Get personalized readings",
    onboardingThirdTitle: "Tarot by AI",
    onboardingThirdTitleMessage: "Get reading about your future",
    skip: "SKIP",
    nextOnboard: "NEXT",
    clinicLoginRedirect: "Continue",
  },
  ro: {
    history: "Istoric",
    selectLanguage: "Alege limba",
    firebaseErrorInvalidCredentials:
      "Credențiale invalide, e-mailul sau parola nu sunt corecte. Dacă crezi că e-mailul este bun, încearcă să resetezi parola.",

    loginNowNoAccount: "Autentificare fără cont",
    motivationalQuoteOfTheDay: "Citat motivațional al zilei",
    luckyColorOfTheDay: "Culoarea norocoasă a zilei",
    luckyHours: "Ore norocoase",
    motivationalQuotes: "Citate Motivationale",
    //AUTH
    firebaseErrorInvalidEmail: "Adresa de email introdusă este invalidă.",
    firebaseErrorEmailAlreadyInUse:
      "Există deja un cont asociat cu această adresă de email.",
    firebaseErrorWeakPassword: "Parola introdusă este prea slabă.",
    firebaseErrorUserNotFound:
      "Nu s-a găsit niciun utilizator cu această adresă de email.",
    firebaseErrorUserDisabled: "Acest utilizator a fost dezactivat.",
    firebaseErrorWrongPassword:
      "Parolă incorectă. Vă rugăm să încercați din nou.",
    firebaseErrorTooManyRequests:
      "Prea multe solicitări. Vă rugăm să încercați din nou mai târziu.",
    firebaseErrorOperationNotAllowed:
      "Operațiunea nu este permisă. Vă rugăm să contactați suportul.",
    firebaseErrorNetworkRequestFailed:
      "Eroare de rețea. Vă rugăm să verificați conexiunea la internet.",
    firebaseErrorUnknown:
      "A apărut o eroare necunoscută. Vă rugăm să încercați din nou.",
    //AUTH

    personalReading: "Citire personalizată",
    futureReading: "Citire de viitor",
    luckyNumber: "Numărul norocos",
    luckyColor: "Culoarea norocoasă",
    touchToShuffle: "Atinge pentru amestecare",
    helloUser: "Salut",
    //new
    login: "Autentificare",
    email: "E-mail",
    password: "Parolă",
    forgotPassword: "Ți-ai uitat parola?",
    dntHaveAccount: "Nu ai un cont?",
    signUp: "Înregistrare",
    loginNow: "Autentificare",
    alreadyAccount: "Ai deja un cont?",
    registerLogin: "Intră în cont",
    register: "Înregistrare",
    myAccount: "Contul Meu",
    currentPassword: "Parola Actuală",
    createPassword: "Parolă Nouă",
    confirmPassword: "Confirmă Parola",
    firstName: "Prenume",
    lastName: "Nume",
    changeEmail: "Schimbă e-mailul",
    changePassword: "Schimbă parola",
    changePhoneNumber: "Schimbă numărul de telefon",
    deleteAccount: "Șterge contul",
    logOut: "Deconectare",
    settings: "Setări",
    saveChanges: "Salvează Modificările",
    passDontMatch: "Parolele nu se potrivesc",
    enterPasswordCurrent: "Introdu Parola Actuală",
    resetPassword: "Resetează Parola",
    backToLogin: "Înapoi la Autentificare",
    historyPersonalized: "Istoric - lectură personalizată",
    historyFuture: "Istoric - lectură viitoare",
    historyTypePersonalized: "Lectură Personalizată",
    historyTypeFuture: "Lectură despre Viitor",
    welcomeTo: "Bun Venit la",
    tarotByAi: "Tarot prin AI",
    onboardingFirstTitle: "Bun Venit la",
    onboardingFirstTitleMessage: "Tarot prin AI",
    onboardingSecondTitle: "Tarot prin AI",
    onboardingSecondTitleMessage: "Obțineți lecturi personalizate",
    onboardingThirdTitle: "Tarot prin AI",
    onboardingThirdTitleMessage: "Obțineți lecturi despre viitorul tău",
    skip: "OMITE",
    nextOnboard: "URMĂTORUL",
    clinicLoginRedirect: "Continuă",
  },
  es: {
    history: "Historial",
    selectLanguage: "Seleccionar idioma",
    firebaseErrorInvalidCredentials:
      "Credenciales inválidas, el correo electrónico o la contraseña no son correctos. Si crees que el correo es correcto, intenta restablecer la contraseña.",

    loginNowNoAccount: "Iniciar sesión sin una cuenta",
    motivationalQuoteOfTheDay: "Frase motivacional del día",
    luckyColorOfTheDay: "Color de la suerte del día",
    luckyHours: "Horas de suerte",
    motivationalQuotes: "Citas Motivacionales",
    //AUTH
    firebaseErrorInvalidEmail:
      "La dirección de correo electrónico es inválida.",
    firebaseErrorEmailAlreadyInUse:
      "Ya existe una cuenta con esta dirección de correo electrónico.",
    firebaseErrorWeakPassword: "La contraseña es demasiado débil.",
    firebaseErrorUserNotFound:
      "No se encontró ningún usuario con esta dirección de correo electrónico.",
    firebaseErrorUserDisabled: "Este usuario ha sido deshabilitado.",
    firebaseErrorWrongPassword:
      "Contraseña incorrecta. Por favor, inténtalo de nuevo.",
    firebaseErrorTooManyRequests:
      "Demasiadas solicitudes. Por favor, inténtalo de nuevo más tarde.",
    firebaseErrorOperationNotAllowed:
      "Operación no permitida. Por favor, contacta con el soporte.",
    firebaseErrorNetworkRequestFailed:
      "Error de red. Por favor, verifica tu conexión a internet.",
    firebaseErrorUnknown:
      "Ocurrió un error desconocido. Por favor, inténtalo de nuevo.",
    //AUTH
    personalReading: "Lectura personalizada",
    futureReading: "Lectura del futuro",
    luckyNumber: "Número de la suerte",
    luckyColor: "Color de la suerte",
    touchToShuffle: "Toca para mezclar",
    helloUser: "Hola",
    //new
    login: "Autenticación",
    email: "Correo Electrónico",
    password: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    dntHaveAccount: "¿No tienes una cuenta?",
    signUp: "Regístrate",
    loginNow: "Inicia sesión",
    alreadyAccount: "¿Ya tienes una cuenta?",
    registerLogin: "Acceder a la cuenta",
    register: "Registro",
    myAccount: "Mi Cuenta",
    currentPassword: "Contraseña Actual",
    createPassword: "Nueva Contraseña",
    confirmPassword: "Confirma la Contraseña",
    firstName: "Nombre",
    lastName: "Apellido",
    changeEmail: "Cambiar correo electrónico",
    changePassword: "Cambiar contraseña",
    changePhoneNumber: "Cambiar número de teléfono",
    deleteAccount: "Eliminar cuenta",
    logOut: "Cerrar sesión",
    settings: "Ajustes",
    saveChanges: "Guardar Cambios",
    passDontMatch: "Las contraseñas no coinciden",
    enterPasswordCurrent: "Introduce la Contraseña Actual",
    resetPassword: "Restablecer Contraseña",
    backToLogin: "Volver a Iniciar Sesión",
    historyPersonalized: "Historial - lectura personalizada",
    historyFuture: "Historial - lectura futura",
    historyTypePersonalized: "Lectura Personalizada",
    historyTypeFuture: "Lectura sobre el Futuro",
    welcomeTo: "Bienvenido a",
    tarotByAi: "Tarot por AI",
    onboardingFirstTitle: "Bienvenido a",
    onboardingFirstTitleMessage: "Tarot por AI",
    onboardingSecondTitle: "Tarot por AI",
    onboardingSecondTitleMessage: "Obtén lecturas personalizadas",
    onboardingThirdTitle: "Tarot por AI",
    onboardingThirdTitleMessage: "Obtén lecturas sobre tu futuro",
    skip: "OMITIR",
    nextOnboard: "SIGUIENTE",
    clinicLoginRedirect: "Continuar",
  },
  it: {
    history: "Storia",
    selectLanguage: "Seleziona Lingua",
    firebaseErrorInvalidCredentials:
      "Credenziali non valide, email o password non corrette. Se pensi che l'email sia corretta prova a reimpostare la password",
    loginNowNoAccount: "Accedi senza account",
    motivationalQuoteOfTheDay: "Citazione motivazionale del giorno",
    luckyColorOfTheDay: "Colore fortunato del giorno",
    luckyHours: "Ore fortunate",
    motivationalQuotes: "Citazioni motivazionali",
    //AUTH
    firebaseErrorInvalidEmail: "L'indirizzo email non è valido.",
    firebaseErrorEmailAlreadyInUse:
      "Un account con questo indirizzo email esiste già.",
    firebaseErrorWeakPassword: "La password è troppo debole.",
    firebaseErrorUserNotFound:
      "Nessun utente trovato con questo indirizzo email.",
    firebaseErrorUserDisabled: "Questo utente è stato disabilitato.",
    firebaseErrorWrongPassword: "Password errata. Per favore riprova.",
    firebaseErrorTooManyRequests:
      "Troppe richieste. Per favore riprova più tardi.",
    firebaseErrorOperationNotAllowed:
      "Operazione non consentita. Si prega di contattare il supporto.",
    firebaseErrorNetworkRequestFailed:
      "Errore di rete. Si prega di controllare la connessione internet.",
    firebaseErrorUnknown:
      "Si è verificato un errore sconosciuto. Per favore riprova.",
    //AUTH
    personalReading: "Lettura personalizzata",
    futureReading: "Lettura futura",
    luckyNumber: "Numero fortunato",
    luckyColor: "Colore fortunato",
    touchToShuffle: "Tocca per mescolare",
    helloUser: "Ciao",
    //new
    login: "Accesso",
    email: "E-mail",
    password: "Password",
    forgotPassword: "Password dimenticata",
    dntHaveAccount: "Non hai un account?",
    signUp: "Registrati",
    loginNow: "Accedi",
    alreadyAccount: "Hai già un account?",
    registerLogin: "Accedi",
    register: "Registra",
    myAccount: "Il mio account",
    currentPassword: "Password attuale",
    createPassword: "Nuova password",
    confirmPassword: "Conferma password",
    firstName: "Nome",
    lastName: "Cognome",
    changeEmail: "Cambia e-mail",
    changePassword: "Cambia password",
    changePhoneNumber: "Cambia numero di telefono",
    deleteAccount: "Elimina account",
    logOut: "Disconnettersi",
    settings: "Impostazioni",
    saveChanges: "Salva le modifiche",
    passDontMatch: "Le password non corrispondono",
    enterPasswordCurrent: "Inserisci la password attuale",
    resetPassword: "Reimposta password",
    backToLogin: "Torna al login",
    historyPersonalized: "Storia - lettura personalizzata",
    historyFuture: "Storia - lettura futura",
    historyTypePersonalized: "Lettura personalizzata",
    historyTypeFuture: "Lettura futura",
    welcomeTo: "Benvenuto in",
    tarotByAi: "Tarocchi di AI",
    onboardingFirstTitle: "Benvenuto in",
    onboardingFirstTitleMessage: "Tarocchi di AI",
    onboardingSecondTitle: "Tarocchi di AI",
    onboardingSecondTitleMessage: "Ottieni letture personalizzate",
    onboardingThirdTitle: "Tarocchi di AI",
    onboardingThirdTitleMessage: "Ottieni una lettura sul tuo futuro",
    skip: "SALTA",
    nextOnboard: "PROSSIMO",
    clinicLoginRedirect: "Continua",
  },
  pl: {
    history: "Historia",
    selectLanguage: "Wybierz język",
    firebaseErrorInvalidCredentials:
      "Nieprawidłowe dane uwierzytelniające, e-mail lub hasło są nieprawidłowe. Jeśli uważasz, że e-mail jest poprawny, spróbuj zresetować hasło",
    loginNowNoAccount: "Zaloguj się bez konta",
    motivationalQuoteOfTheDay: "Motywujący cytat dnia",
    luckyColorOfTheDay: "Szczęśliwy kolor dnia",
    luckyHours: "Szczęśliwe godziny",
    motivationalQuotes: "Cytaty motywacyjne",
    //AUTH
    firebaseErrorInvalidEmail: "Adres e-mail jest nieprawidłowy.",
    firebaseErrorEmailAlreadyInUse: "Konto już istnieje z tym adresem e-mail.",
    firebaseErrorWeakPassword: "Hasło jest zbyt słabe.",
    firebaseErrorUserNotFound:
      "Nie znaleziono użytkownika z tym adresem e-mail.",
    firebaseErrorUserDisabled: "Ten użytkownik został wyłączony.",
    firebaseErrorWrongPassword:
      "Nieprawidłowe hasło. Proszę spróbować ponownie.",
    firebaseErrorTooManyRequests:
      "Zbyt wiele prób. Proszę spróbować ponownie później.",
    firebaseErrorOperationNotAllowed:
      "Operacja niedozwolona. Proszę skontaktować się z pomocą.",
    firebaseErrorNetworkRequestFailed:
      "Błąd sieci. Proszę sprawdzić swoje połączenie internetowe.",
    firebaseErrorUnknown: "Wystąpił nieznany błąd. Proszę spróbować ponownie.",
    //AUTH
    personalReading: "Osobista lektura",
    futureReading: "Lektura przyszłości",
    luckyNumber: "Szczęśliwy numer",
    luckyColor: "Szczęśliwy kolor",
    touchToShuffle: "Dotknij, aby tasować",
    helloUser: "Witaj",
    //new
    login: "Logowanie",
    email: "E-mail",
    password: "Hasło",
    forgotPassword: "Zapomniane hasło",
    dntHaveAccount: "Nie masz konta?",
    signUp: "Zarejestruj się",
    loginNow: "Zaloguj się",
    alreadyAccount: "Masz już konto?",
    registerLogin: "Zaloguj się",
    register: "Zarejestruj",
    myAccount: "Moje konto",
    currentPassword: "Aktualne hasło",
    createPassword: "Utwórz hasło",
    confirmPassword: "Potwierdź hasło",
    firstName: "Imię",
    lastName: "Nazwisko",
    changeEmail: "Zmień e-mail",
    changePassword: "Zmień hasło",
    changePhoneNumber: "Zmień numer telefonu",
    deleteAccount: "Usuń konto",
    logOut: "Wyloguj się",
    settings: "Ustawienia",
    saveChanges: "Zapisz zmiany",
    passDontMatch: "Hasła nie pasują",
    enterPasswordCurrent: "Wpisz aktualne hasło",
    resetPassword: "Zresetuj hasło",
    backToLogin: "Powrót do logowania",
    historyPersonalized: "Historia - osobista lektura",
    historyFuture: "Historia - lektura przyszłości",
    historyTypePersonalized: "Osobista lektura",
    historyTypeFuture: "Lektura przyszłości",
    welcomeTo: "Witamy w",
    tarotByAi: "Tarot przez AI",
    onboardingFirstTitle: "Witamy w",
    onboardingFirstTitleMessage: "Tarot przez AI",
    onboardingSecondTitle: "Tarot przez AI",
    onboardingSecondTitleMessage: "Otrzymuj spersonalizowane czytania",
    onboardingThirdTitle: "Tarot przez AI",
    onboardingThirdTitleMessage:
      "Otrzymaj czytanie na temat swojej przyszłości",
    skip: "POMIŃ",
    nextOnboard: "NASTĘPNY",
    clinicLoginRedirect: "Kontynuuj",
  },
  bg: {
    history: "История",
    selectLanguage: "Изберете език",
    firebaseErrorInvalidCredentials:
      "Невалидни данни, имейлът или паролата не са правилни. Ако мислите, че имейлът е правилен, опитайте да нулирате паролата",
    loginNowNoAccount: "Вход без акаунт",
    motivationalQuoteOfTheDay: "Мотивиращ цитат на деня",
    luckyColorOfTheDay: "Късметлийски цвят на деня",
    luckyHours: "Късметлийски часове",
    motivationalQuotes: "Мотивиращи цитати",
    //AUTH
    firebaseErrorInvalidEmail: "Имейл адресът е невалиден.",
    firebaseErrorEmailAlreadyInUse:
      "Вече съществува акаунт с този имейл адрес.",
    firebaseErrorWeakPassword: "Паролата е твърде слаба.",
    firebaseErrorUserNotFound: "Не е намерен потребител с този имейл адрес.",
    firebaseErrorUserDisabled: "Този потребител е деактивиран.",
    firebaseErrorWrongPassword: "Грешна парола. Моля, опитайте отново.",
    firebaseErrorTooManyRequests:
      "Твърде много заявки. Моля, опитайте по-късно.",
    firebaseErrorOperationNotAllowed:
      "Операцията не е позволена. Моля, свържете се с поддръжката.",
    firebaseErrorNetworkRequestFailed:
      "Грешка в мрежата. Моля, проверете интернет връзката си.",
    firebaseErrorUnknown: "Възникна неизвестна грешка. Моля, опитайте отново.",
    //AUTH
    personalReading: "Персонализирано четене",
    futureReading: "Четене за бъдещето",
    luckyNumber: "Късметлийски номер",
    luckyColor: "Късметлийски цвят",
    touchToShuffle: "Докоснете за разбъркване",
    helloUser: "Здравей",
    //new
    login: "Вход",
    email: "Имейл",
    password: "Парола",
    forgotPassword: "Забравена парола",
    dntHaveAccount: "Нямате акаунт?",
    signUp: "Регистрирайте се",
    loginNow: "Вход",
    alreadyAccount: "Вече имате акаунт?",
    registerLogin: "Влезте",
    register: "Регистрирайте",
    myAccount: "Моят акаунт",
    currentPassword: "Текуща парола",
    createPassword: "Нова парола",
    confirmPassword: "Потвърдете паролата",
    firstName: "Име",
    lastName: "Фамилия",
    changeEmail: "Сменете имейла",
    changePassword: "Сменете паролата",
    changePhoneNumber: "Сменете телефонния номер",
    deleteAccount: "Изтрийте акаунта",
    logOut: "Изход",
    settings: "Настройки",
    saveChanges: "Запазете промените",
    passDontMatch: "Паролите не съвпадат",
    enterPasswordCurrent: "Въведете текущата парола",
    resetPassword: "Нулиране на паролата",
    backToLogin: "Обратно към входа",
    historyPersonalized: "История - персонализирано четене",
    historyFuture: "История - четене за бъдещето",
    historyTypePersonalized: "Персонализирано четене",
    historyTypeFuture: "Четене за бъдещето",
    welcomeTo: "Добре дошли в",
    tarotByAi: "Таро от AI",
    onboardingFirstTitle: "Добре дошли в",
    onboardingFirstTitleMessage: "Таро от AI",
    onboardingSecondTitle: "Таро от AI",
    onboardingSecondTitleMessage: "Получавайте персонализирани четения",
    onboardingThirdTitle: "Таро от AI",
    onboardingThirdTitleMessage: "Получете четене за вашето бъдеще",
    skip: "ПРОПУСНИ",
    nextOnboard: "СЛЕДВАЩ",
    clinicLoginRedirect: "Продължете",
  },
  cs: {
    history: "Historie",
    selectLanguage: "Vybrat jazyk",
    firebaseErrorInvalidCredentials:
      "Neplatné přihlašovací údaje, email nebo heslo nejsou správné. Pokud si myslíte, že email je správný, zkuste resetovat heslo",
    loginNowNoAccount: "Přihlásit se bez účtu",
    motivationalQuoteOfTheDay: "Motivační citát dne",
    luckyColorOfTheDay: "Šťastná barva dne",
    luckyHours: "Šťastné hodiny",
    motivationalQuotes: "Motivační citáty",
    //AUTH
    firebaseErrorInvalidEmail: "Emailová adresa je neplatná.",
    firebaseErrorEmailAlreadyInUse:
      "Účet s touto emailovou adresou již existuje.",
    firebaseErrorWeakPassword: "Heslo je příliš slabé.",
    firebaseErrorUserNotFound:
      "Nenalezen žádný uživatel s touto emailovou adresou.",
    firebaseErrorUserDisabled: "Tento uživatel byl deaktivován.",
    firebaseErrorWrongPassword: "Nesprávné heslo. Zkuste to prosím znovu.",
    firebaseErrorTooManyRequests:
      "Příliš mnoho požadavků. Zkuste to prosím později.",
    firebaseErrorOperationNotAllowed:
      "Operace není povolena. Prosím, kontaktujte podporu.",
    firebaseErrorNetworkRequestFailed:
      "Chyba sítě. Prosím, zkontrolujte své internetové připojení.",
    firebaseErrorUnknown: "Došlo k neznámé chybě. Zkuste to prosím znovu.",
    //AUTH
    personalReading: "Personalizované čtení",
    futureReading: "Čtení budoucnosti",
    luckyNumber: "Šťastné číslo",
    luckyColor: "Šťastná barva",
    touchToShuffle: "Dotkněte se pro zamíchání",
    helloUser: "Ahoj",
    //new
    login: "Přihlásit se",
    email: "E-mail",
    password: "Heslo",
    forgotPassword: "Zapomenuté heslo",
    dntHaveAccount: "Nemáte účet?",
    signUp: "Zaregistrovat",
    loginNow: "Přihlásit se",
    alreadyAccount: "Již máte účet?",
    registerLogin: "Přihlásit se",
    register: "Zaregistrovat",
    myAccount: "Můj účet",
    currentPassword: "Současné heslo",
    createPassword: "Nové heslo",
    confirmPassword: "Potvrdit heslo",
    firstName: "Jméno",
    lastName: "Příjmení",
    changeEmail: "Změnit e-mail",
    changePassword: "Změnit heslo",
    changePhoneNumber: "Změnit telefonní číslo",
    deleteAccount: "Smazat účet",
    logOut: "Odhlásit se",
    settings: "Nastavení",
    saveChanges: "Uložit změny",
    passDontMatch: "Hesla se neshodují",
    enterPasswordCurrent: "Zadejte současné heslo",
    resetPassword: "Resetovat heslo",
    backToLogin: "Zpět na přihlášení",
    historyPersonalized: "Historie - personalizované čtení",
    historyFuture: "Historie - čtení budoucnosti",
    historyTypePersonalized: "Personalizované čtení",
    historyTypeFuture: "Čtení budoucnosti",
    welcomeTo: "Vítejte v",
    tarotByAi: "Tarot od AI",
    onboardingFirstTitle: "Vítejte v",
    onboardingFirstTitleMessage: "Tarot od AI",
    onboardingSecondTitle: "Tarot od AI",
    onboardingSecondTitleMessage: "Získejte personalizované čtení",
    onboardingThirdTitle: "Tarot od AI",
    onboardingThirdTitleMessage: "Získejte čtení o vaší budoucnosti",
    skip: "PŘESKOČIT",
    nextOnboard: "DALŠÍ",
    clinicLoginRedirect: "Pokračovat",
  },
  de: {
    history: "Geschichte",
    selectLanguage: "Sprache auswählen",
    firebaseErrorInvalidCredentials:
      "Ungültige Anmeldeinformationen, E-Mail oder Passwort nicht korrekt. Wenn Sie denken, dass die E-Mail korrekt ist, versuchen Sie das Passwort zurückzusetzen",
    loginNowNoAccount: "Ohne Konto anmelden",
    motivationalQuoteOfTheDay: "Motivationszitat des Tages",
    luckyColorOfTheDay: "Glücksfarbe des Tages",
    luckyHours: "Glücksstunden",
    motivationalQuotes: "Motivationszitate",
    //AUTH
    firebaseErrorInvalidEmail: "Die E-Mail-Adresse ist ungültig.",
    firebaseErrorEmailAlreadyInUse:
      "Ein Konto mit dieser E-Mail-Adresse existiert bereits.",
    firebaseErrorWeakPassword: "Das Passwort ist zu schwach.",
    firebaseErrorUserNotFound:
      "Kein Benutzer mit dieser E-Mail-Adresse gefunden.",
    firebaseErrorUserDisabled: "Dieser Benutzer wurde deaktiviert.",
    firebaseErrorWrongPassword:
      "Falsches Passwort. Bitte versuchen Sie es erneut.",
    firebaseErrorTooManyRequests:
      "Zu viele Anfragen. Bitte später noch einmal versuchen.",
    firebaseErrorOperationNotAllowed:
      "Vorgang nicht erlaubt. Bitte kontaktieren Sie den Support.",
    firebaseErrorNetworkRequestFailed:
      "Netzwerkfehler. Bitte überprüfen Sie Ihre Internetverbindung.",
    firebaseErrorUnknown:
      "Ein unbekannter Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    //AUTH
    personalReading: "Persönliches Lesen",
    futureReading: "Zukünftiges Lesen",
    luckyNumber: "Glückszahl",
    luckyColor: "Glücksfarbe",
    touchToShuffle: "Zum Mischen berühren",
    helloUser: "Hallo",
    //new
    login: "Anmelden",
    email: "E-Mail",
    password: "Passwort",
    forgotPassword: "Passwort vergessen",
    dntHaveAccount: "Kein Konto?",
    signUp: "Registrieren",
    loginNow: "Anmelden",
    alreadyAccount: "Bereits ein Konto?",
    registerLogin: "Einloggen",
    register: "Registrieren",
    myAccount: "Mein Konto",
    currentPassword: "Aktuelles Passwort",
    createPassword: "Neues Passwort",
    confirmPassword: "Passwort bestätigen",
    firstName: "Vorname",
    lastName: "Nachname",
    changeEmail: "E-Mail ändern",
    changePassword: "Passwort ändern",
    changePhoneNumber: "Telefonnummer ändern",
    deleteAccount: "Konto löschen",
    logOut: "Ausloggen",
    settings: "Einstellungen",
    saveChanges: "Änderungen speichern",
    passDontMatch: "Passwörter stimmen nicht überein",
    enterPasswordCurrent: "Aktuelles Passwort eingeben",
    resetPassword: "Passwort zurücksetzen",
    backToLogin: "Zurück zum Anmelden",
    historyPersonalized: "Geschichte - personalisiertes Lesen",
    historyFuture: "Geschichte - zukünftiges Lesen",
    historyTypePersonalized: "Personalisiertes Lesen",
    historyTypeFuture: "Zukünftiges Lesen",
    welcomeTo: "Willkommen bei",
    tarotByAi: "Tarot von AI",
    onboardingFirstTitle: "Willkommen bei",
    onboardingFirstTitleMessage: "Tarot von AI",
    onboardingSecondTitle: "Tarot von AI",
    onboardingSecondTitleMessage: "Erhalten Sie personalisierte Lesungen",
    onboardingThirdTitle: "Tarot von AI",
    onboardingThirdTitleMessage: "Lesen Sie über Ihre Zukunft",
    skip: "ÜBERSPRINGEN",
    nextOnboard: "WEITER",
    clinicLoginRedirect: "Fortfahren",
  },
  el: {
    history: "Ιστορία",
    selectLanguage: "Επιλογή Γλώσσας",
    firebaseErrorInvalidCredentials:
      "Άκυρα διαπιστευτήρια, το email ή ο κωδικός πρόσβασης δεν είναι σωστά. Εάν πιστεύετε ότι το email είναι σωστό, δοκιμάστε να επαναφέρετε τον κωδικό πρόσβασης",
    loginNowNoAccount: "Σύνδεση χωρίς λογαριασμό",
    motivationalQuoteOfTheDay: "Κινητήριος απόφθεγμα της ημέρας",
    luckyColorOfTheDay: "Τυχερό χρώμα της ημέρας",
    luckyHours: "Τυχερές Ώρες",
    motivationalQuotes: "Κινητήρια Αποφθέγματα",
    //AUTH
    firebaseErrorInvalidEmail: "Η διεύθυνση email είναι άκυρη.",
    firebaseErrorEmailAlreadyInUse:
      "Ένας λογαριασμός με αυτήν τη διεύθυνση email υπάρχει ήδη.",
    firebaseErrorWeakPassword: "Ο κωδικός πρόσβασης είναι πολύ αδύναμος.",
    firebaseErrorUserNotFound:
      "Δεν βρέθηκε χρήστης με αυτήν τη διεύθυνση email.",
    firebaseErrorUserDisabled: "Αυτός ο χρήστης έχει απενεργοποιηθεί.",
    firebaseErrorWrongPassword:
      "Λάθος κωδικός πρόσβασης. Παρακαλώ δοκιμάστε ξανά.",
    firebaseErrorTooManyRequests:
      "Πάρα πολλά αιτήματα. Παρακαλώ δοκιμάστε ξανά αργότερα.",
    firebaseErrorOperationNotAllowed:
      "Η λειτουργία δεν επιτρέπεται. Παρακαλώ επικοινωνήστε με την υποστήριξη.",
    firebaseErrorNetworkRequestFailed:
      "Σφάλμα δικτύου. Παρακαλώ ελέγξτε τη σύνδεση σας στο διαδίκτυο.",
    firebaseErrorUnknown:
      "Παρουσιάστηκε άγνωστο σφάλμα. Παρακαλώ δοκιμάστε ξανά.",
    //AUTH
    personalReading: "Προσωπική Ανάγνωση",
    futureReading: "Ανάγνωση Μέλλοντος",
    luckyNumber: "Τυχερός Αριθμός",
    luckyColor: "Τυχερό Χρώμα",
    touchToShuffle: "Αγγίξτε για ανακάτεμα",
    helloUser: "Γεια",
    //new
    login: "Σύνδεση",
    email: "E-mail",
    password: "Κωδικός Πρόσβασης",
    forgotPassword: "Ξεχάσατε τον Κωδικό",
    dntHaveAccount: "Δεν έχετε λογαριασμό;",
    signUp: "Εγγραφή",
    loginNow: "Σύνδεση",
    alreadyAccount: "Έχετε ήδη λογαριασμό;",
    registerLogin: "Σύνδεση",
    register: "Εγγραφή",
    myAccount: "Ο Λογαριασμός μου",
    currentPassword: "Τρέχων Κωδικός",
    createPassword: "Νέος Κωδικός",
    confirmPassword: "Επιβεβαίωση Κωδικού",
    firstName: "Όνομα",
    lastName: "Επώνυμο",
    changeEmail: "Αλλαγή E-mail",
    changePassword: "Αλλαγή Κωδικού",
    changePhoneNumber: "Αλλαγή Αριθμού Τηλεφώνου",
    deleteAccount: "Διαγραφή Λογαριασμού",
    logOut: "Αποσύνδεση",
    settings: "Ρυθμίσεις",
    saveChanges: "Αποθήκευση Αλλαγών",
    passDontMatch: "Οι κωδικοί δεν ταιριάζουν",
    enterPasswordCurrent: "Εισάγετε Τρέχων Κωδικό",
    resetPassword: "Επαναφορά Κωδικού",
    backToLogin: "Επιστροφή στη Σύνδεση",
    historyPersonalized: "Ιστορικό - Προσωπική Ανάγνωση",
    historyFuture: "Ιστορικό - Ανάγνωση Μέλλοντος",
    historyTypePersonalized: "Προσωπική Ανάγνωση",
    historyTypeFuture: "Ανάγνωση Μέλλοντος",
    welcomeTo: "Καλωσορίσατε στο",
    tarotByAi: "Ταρώ από AI",
    onboardingFirstTitle: "Καλωσορίσατε στο",
    onboardingFirstTitleMessage: "Ταρώ από AI",
    onboardingSecondTitle: "Ταρώ από AI",
    onboardingSecondTitleMessage: "Λάβετε προσωπικές αναγνώσεις",
    onboardingThirdTitle: "Ταρώ από AI",
    onboardingThirdTitleMessage: "Λάβετε ανάγνωση για το μέλλον σας",
    skip: "ΠΑΡΑΛΕΙΨΗ",
    nextOnboard: "ΕΠΟΜΕΝΟ",
    clinicLoginRedirect: "Συνέχεια",
  },
  fr: {
    history: "Histoire",
    selectLanguage: "Sélectionner la langue",
    firebaseErrorInvalidCredentials:
      "Identifiants invalides, e-mail ou mot de passe incorrects. Si vous pensez que l'e-mail est correct, essayez de réinitialiser le mot de passe",
    loginNowNoAccount: "Connexion sans compte",
    motivationalQuoteOfTheDay: "Citation motivante du jour",
    luckyColorOfTheDay: "Couleur chanceuse du jour",
    luckyHours: "Heures chanceuses",
    motivationalQuotes: "Citations motivantes",
    //AUTH
    firebaseErrorInvalidEmail: "L'adresse e-mail est invalide.",
    firebaseErrorEmailAlreadyInUse:
      "Un compte existe déjà avec cette adresse e-mail.",
    firebaseErrorWeakPassword: "Le mot de passe est trop faible.",
    firebaseErrorUserNotFound:
      "Aucun utilisateur trouvé avec cette adresse e-mail.",
    firebaseErrorUserDisabled: "Cet utilisateur a été désactivé.",
    firebaseErrorWrongPassword: "Mot de passe incorrect. Veuillez réessayer.",
    firebaseErrorTooManyRequests:
      "Trop de demandes. Veuillez réessayer plus tard.",
    firebaseErrorOperationNotAllowed:
      "Opération non autorisée. Veuillez contacter le support.",
    firebaseErrorNetworkRequestFailed:
      "Erreur de réseau. Veuillez vérifier votre connexion Internet.",
    firebaseErrorUnknown:
      "Une erreur inconnue s'est produite. Veuillez réessayer.",
    //AUTH
    personalReading: "Lecture personnalisée",
    futureReading: "Lecture de l'avenir",
    luckyNumber: "Numéro chanceux",
    luckyColor: "Couleur chanceuse",
    touchToShuffle: "Touchez pour mélanger",
    helloUser: "Bonjour",
    //new
    login: "Connexion",
    email: "E-mail",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié",
    dntHaveAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    loginNow: "Connexion",
    alreadyAccount: "Vous avez déjà un compte ?",
    registerLogin: "Se connecter",
    register: "S'inscrire",
    myAccount: "Mon compte",
    currentPassword: "Mot de passe actuel",
    createPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    firstName: "Prénom",
    lastName: "Nom de famille",
    changeEmail: "Changer d'e-mail",
    changePassword: "Changer de mot de passe",
    changePhoneNumber: "Changer de numéro de téléphone",
    deleteAccount: "Supprimer le compte",
    logOut: "Se déconnecter",
    settings: "Paramètres",
    saveChanges: "Enregistrer les modifications",
    passDontMatch: "Les mots de passe ne correspondent pas",
    enterPasswordCurrent: "Entrez le mot de passe actuel",
    resetPassword: "Réinitialiser le mot de passe",
    backToLogin: "Retour à la connexion",
    historyPersonalized: "Histoire - lecture personnalisée",
    historyFuture: "Histoire - lecture de l'avenir",
    historyTypePersonalized: "Lecture personnalisée",
    historyTypeFuture: "Lecture de l'avenir",
    welcomeTo: "Bienvenue à",
    tarotByAi: "Tarot par AI",
    onboardingFirstTitle: "Bienvenue à",
    onboardingFirstTitleMessage: "Tarot par AI",
    onboardingSecondTitle: "Tarot par AI",
    onboardingSecondTitleMessage: "Obtenez des lectures personnalisées",
    onboardingThirdTitle: "Tarot par AI",
    onboardingThirdTitleMessage: "Obtenez une lecture sur votre avenir",
    skip: "PASSER",
    nextOnboard: "SUIVANT",
    clinicLoginRedirect: "Continuer",
  },
  hr: {
    history: "Povijest",
    selectLanguage: "Odaberite jezik",
    firebaseErrorInvalidCredentials:
      "Nevažeći vjerodajnice, email ili lozinka nisu dobri. Ako mislite da je email ispravan, pokušajte resetirati lozinku",
    loginNowNoAccount: "Prijava bez računa",
    motivationalQuoteOfTheDay: "Motivacijski citat dana",
    luckyColorOfTheDay: "Sretna boja dana",
    luckyHours: "Sretni sati",
    motivationalQuotes: "Motivacijski citati",
    //AUTH
    firebaseErrorInvalidEmail: "Adresa e-pošte je nevažeća.",
    firebaseErrorEmailAlreadyInUse: "Račun s ovom adresom e-pošte već postoji.",
    firebaseErrorWeakPassword: "Lozinka je preslaba.",
    firebaseErrorUserNotFound: "Nije pronađen korisnik s ovom adresom e-pošte.",
    firebaseErrorUserDisabled: "Ovaj korisnik je onemogućen.",
    firebaseErrorWrongPassword: "Netočna lozinka. Molimo pokušajte ponovno.",
    firebaseErrorTooManyRequests: "Previše zahtjeva. Molimo pokušajte kasnije.",
    firebaseErrorOperationNotAllowed:
      "Operacija nije dopuštena. Molimo kontaktirajte podršku.",
    firebaseErrorNetworkRequestFailed:
      "Greška u mreži. Molimo provjerite svoju internetsku vezu.",
    firebaseErrorUnknown:
      "Došlo je do nepoznate pogreške. Molimo pokušajte ponovno.",
    //AUTH
    personalReading: "Osobno čitanje",
    futureReading: "Čitanje budućnosti",
    luckyNumber: "Sretan broj",
    luckyColor: "Sretna boja",
    touchToShuffle: "Dodirnite za miješanje",
    helloUser: "Pozdrav",
    //new
    login: "Prijava",
    email: "E-mail",
    password: "Lozinka",
    forgotPassword: "Zaboravljena lozinka",
    dntHaveAccount: "Nemate račun?",
    signUp: "Registrirajte se",
    loginNow: "Prijava",
    alreadyAccount: "Već imate račun?",
    registerLogin: "Prijavite se",
    register: "Registracija",
    myAccount: "Moj račun",
    currentPassword: "Trenutna lozinka",
    createPassword: "Nova lozinka",
    confirmPassword: "Potvrdite lozinku",
    firstName: "Ime",
    lastName: "Prezime",
    changeEmail: "Promijenite e-mail",
    changePassword: "Promijenite lozinku",
    changePhoneNumber: "Promijenite broj telefona",
    deleteAccount: "Izbrišite račun",
    logOut: "Odjava",
    settings: "Postavke",
    saveChanges: "Spremi promjene",
    passDontMatch: "Lozinke se ne podudaraju",
    enterPasswordCurrent: "Unesite trenutnu lozinku",
    resetPassword: "Resetirajte lozinku",
    backToLogin: "Natrag na prijavu",
    historyPersonalized: "Povijest - osobno čitanje",
    historyFuture: "Povijest - čitanje budućnosti",
    historyTypePersonalized: "Osobno čitanje",
    historyTypeFuture: "Čitanje budućnosti",
    welcomeTo: "Dobrodošli u",
    tarotByAi: "Tarot od AI",
    onboardingFirstTitle: "Dobrodošli u",
    onboardingFirstTitleMessage: "Tarot od AI",
    onboardingSecondTitle: "Tarot od AI",
    onboardingSecondTitleMessage: "Dobijte personalizirana čitanja",
    onboardingThirdTitle: "Tarot od AI",
    onboardingThirdTitleMessage: "Dobijte čitanje o svojoj budućnosti",
    skip: "PRESKOČI",
    nextOnboard: "SLJEDEĆE",
    clinicLoginRedirect: "Nastavi",
  },
  hi: {
    history: "इतिहास",
    selectLanguage: "भाषा चुनें",
    firebaseErrorInvalidCredentials:
      "अमान्य प्रमाण-पत्र, ईमेल या पासवर्ड सही नहीं है। अगर आपको लगता है कि ईमेल सही है, तो पासवर्ड रीसेट करने का प्रयास करें",
    loginNowNoAccount: "खाता नहीं होने पर लॉग इन करें",
    motivationalQuoteOfTheDay: "आज का प्रेरक कथन",
    luckyColorOfTheDay: "आज का भाग्यशाली रंग",
    luckyHours: "भाग्यशाली घंटे",
    motivationalQuotes: "प्रेरक कथन",
    //AUTH
    firebaseErrorInvalidEmail: "ईमेल पता अमान्य है।",
    firebaseErrorEmailAlreadyInUse:
      "इस ईमेल पते के साथ पहले से ही एक खाता मौजूद है।",
    firebaseErrorWeakPassword: "पासवर्ड बहुत कमजोर है।",
    firebaseErrorUserNotFound: "इस ईमेल पते के साथ कोई उपयोगकर्ता नहीं मिला।",
    firebaseErrorUserDisabled: "यह उपयोगकर्ता अक्षम किया गया है।",
    firebaseErrorWrongPassword: "गलत पासवर्ड। कृपया पुनः प्रयास करें।",
    firebaseErrorTooManyRequests:
      "बहुत अधिक अनुरोध। कृपया बाद में पुनः प्रयास करें।",
    firebaseErrorOperationNotAllowed:
      "ऑपरेशन अनुमति नहीं। कृपया सहायता से संपर्क करें।",
    firebaseErrorNetworkRequestFailed:
      "नेटवर्क त्रुटि। कृपया अपने इंटरनेट कनेक्शन की जांच करें।",
    firebaseErrorUnknown: "अज्ञात त्रुटि हुई है। कृपया पुनः प्रयास करें।",
    //AUTH
    personalReading: "व्यक्तिगत पठन",
    futureReading: "भविष्य पठन",
    luckyNumber: "भाग्यशाली संख्या",
    luckyColor: "भाग्यशाली रंग",
    touchToShuffle: "मिलाने के लिए स्पर्श करें",
    helloUser: "नमस्ते",
    //new
    login: "लॉग इन करें",
    email: "ईमेल",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए",
    dntHaveAccount: "खाता नहीं है?",
    signUp: "रजिस्टर करें",
    loginNow: "लॉग इन करें",
    alreadyAccount: "पहले से ही खाता है?",
    registerLogin: "साइन इन करें",
    register: "रजिस्टर करें",
    myAccount: "मेरा खाता",
    currentPassword: "वर्तमान पासवर्ड",
    createPassword: "नया पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    changeEmail: "ईमेल बदलें",
    changePassword: "पासवर्ड बदलें",
    changePhoneNumber: "फोन नंबर बदलें",
    deleteAccount: "खाता हटाएं",
    logOut: "लॉग आउट",
    settings: "सेटिंग्स",
    saveChanges: "परिवर्तन सहेजें",
    passDontMatch: "पासवर्ड मेल नहीं खाते",
    enterPasswordCurrent: "वर्तमान पासवर्ड दर्ज करें",
    resetPassword: "पासवर्ड रीसेट करें",
    backToLogin: "लॉगिन पर वापस जाएं",
    historyPersonalized: "इतिहास - व्यक्तिगत पठन",
    historyFuture: "इतिहास - भविष्य पठन",
    historyTypePersonalized: "व्यक्तिगत पठन",
    historyTypeFuture: "भविष्य पठन",
    welcomeTo: "में आपका स्वागत है",
    tarotByAi: "AI द्वारा टैरो",
    onboardingFirstTitle: "में आपका स्वागत है",
    onboardingFirstTitleMessage: "AI द्वारा टैरो",
    onboardingSecondTitle: "AI द्वारा टैरो",
    onboardingSecondTitleMessage: "व्यक्तिगत पठन प्राप्त करें",
    onboardingThirdTitle: "AI द्वारा टैरो",
    onboardingThirdTitleMessage: "अपने भविष्य के बारे में पठन प्राप्त करें",
    skip: "छोड़ें",
    nextOnboard: "अगला",
    clinicLoginRedirect: "जारी रखें",
  },
  id: {
    history: "Sejarah",
    selectLanguage: "Pilih Bahasa",
    firebaseErrorInvalidCredentials:
      "Kredensial tidak valid, email atau kata sandi tidak benar. Jika Anda pikir email sudah benar, coba setel ulang kata sandi Anda",
    loginNowNoAccount: "Masuk tanpa akun",
    motivationalQuoteOfTheDay: "Kutipan Motivasi Hari Ini",
    luckyColorOfTheDay: "Warna Keberuntungan Hari Ini",
    luckyHours: "Jam Keberuntungan",
    motivationalQuotes: "Kutipan Motivasi",
    //AUTH
    firebaseErrorInvalidEmail: "Alamat email tidak valid.",
    firebaseErrorEmailAlreadyInUse: "Akun sudah ada dengan alamat email ini.",
    firebaseErrorWeakPassword: "Kata sandi terlalu lemah.",
    firebaseErrorUserNotFound:
      "Tidak ada pengguna yang ditemukan dengan alamat email ini.",
    firebaseErrorUserDisabled: "Pengguna ini telah dinonaktifkan.",
    firebaseErrorWrongPassword: "Kata sandi salah. Silakan coba lagi.",
    firebaseErrorTooManyRequests:
      "Terlalu banyak permintaan. Silakan coba lagi nanti.",
    firebaseErrorOperationNotAllowed:
      "Operasi tidak diizinkan. Silakan hubungi dukungan.",
    firebaseErrorNetworkRequestFailed:
      "Kesalahan jaringan. Silakan periksa koneksi internet Anda.",
    firebaseErrorUnknown:
      "Terjadi kesalahan yang tidak diketahui. Silakan coba lagi.",
    //AUTH
    personalReading: "Bacaan Pribadi",
    futureReading: "Bacaan Masa Depan",
    luckyNumber: "Nomor Keberuntungan",
    luckyColor: "Warna Keberuntungan",
    touchToShuffle: "Sentuh untuk mengocok",
    helloUser: "Halo",
    //new
    login: "Masuk",
    email: "E-mail",
    password: "Kata Sandi",
    forgotPassword: "Lupa Kata Sandi",
    dntHaveAccount: "Tidak punya akun?",
    signUp: "Daftar",
    loginNow: "Masuk",
    alreadyAccount: "Sudah punya akun?",
    registerLogin: "Masuk",
    register: "Daftar",
    myAccount: "Akun Saya",
    currentPassword: "Kata Sandi Saat Ini",
    createPassword: "Buat Kata Sandi",
    confirmPassword: "Konfirmasi Kata Sandi",
    firstName: "Nama Depan",
    lastName: "Nama Belakang",
    changeEmail: "Ubah E-mail",
    changePassword: "Ubah Kata Sandi",
    changePhoneNumber: "Ubah Nomor Telepon",
    deleteAccount: "Hapus Akun",
    logOut: "Keluar",
    settings: "Pengaturan",
    saveChanges: "Simpan Perubahan",
    passDontMatch: "Kata sandi tidak cocok",
    enterPasswordCurrent: "Masukkan Kata Sandi Saat Ini",
    resetPassword: "Setel Ulang Kata Sandi",
    backToLogin: "Kembali ke Masuk",
    historyPersonalized: "Sejarah - Bacaan Pribadi",
    historyFuture: "Sejarah - Bacaan Masa Depan",
    historyTypePersonalized: "Bacaan Pribadi",
    historyTypeFuture: "Bacaan Masa Depan",
    welcomeTo: "Selamat Datang di",
    tarotByAi: "Tarot oleh AI",
    onboardingFirstTitle: "Selamat Datang di",
    onboardingFirstTitleMessage: "Tarot oleh AI",
    onboardingSecondTitle: "Tarot oleh AI",
    onboardingSecondTitleMessage: "Dapatkan bacaan personalisasi",
    onboardingThirdTitle: "Tarot oleh AI",
    onboardingThirdTitleMessage: "Dapatkan bacaan tentang masa depan Anda",
    skip: "LEWATI",
    nextOnboard: "BERIKUTNYA",
    clinicLoginRedirect: "Lanjutkan",
  },
  sk: {
    history: "História",
    selectLanguage: "Vybrať jazyk",
    firebaseErrorInvalidCredentials:
      "Neplatné poverenia, e-mail alebo heslo nie sú správne. Ak si myslíte, že e-mail je správny, skúste resetovať heslo",
    loginNowNoAccount: "Prihlásiť sa bez účtu",
    motivationalQuoteOfTheDay: "Motivačný citát dňa",
    luckyColorOfTheDay: "Šťastná farba dňa",
    luckyHours: "Šťastné hodiny",
    motivationalQuotes: "Motivačné citáty",
    //AUTH
    firebaseErrorInvalidEmail: "E-mailová adresa je neplatná.",
    firebaseErrorEmailAlreadyInUse:
      "Účet s touto e-mailovou adresou už existuje.",
    firebaseErrorWeakPassword: "Heslo je príliš slabé.",
    firebaseErrorUserNotFound:
      "Nebol nájdený používateľ s touto e-mailovou adresou.",
    firebaseErrorUserDisabled: "Tento používateľ bol deaktivovaný.",
    firebaseErrorWrongPassword: "Nesprávne heslo. Skúste znova.",
    firebaseErrorTooManyRequests:
      "Príliš veľa požiadaviek. Skúste znova neskôr.",
    firebaseErrorOperationNotAllowed:
      "Operácia nie je povolená. Kontaktujte podporu.",
    firebaseErrorNetworkRequestFailed:
      "Chyba siete. Skontrolujte svoje internetové pripojenie.",
    firebaseErrorUnknown: "Vyskytla sa neznáma chyba. Skúste znova.",
    //AUTH
    personalReading: "Personalizované čítanie",
    futureReading: "Čítanie budúcnosti",
    luckyNumber: "Šťastné číslo",
    luckyColor: "Šťastná farba",
    touchToShuffle: "Dotknite sa na zamiešanie",
    helloUser: "Ahoj",
    //new
    login: "Prihlásiť sa",
    email: "E-mail",
    password: "Heslo",
    forgotPassword: "Zabudnuté heslo",
    dntHaveAccount: "Nemáte účet?",
    signUp: "Zaregistrovať sa",
    loginNow: "Prihlásiť sa",
    alreadyAccount: "Už máte účet?",
    registerLogin: "Prihlásiť sa",
    register: "Zaregistrovať",
    myAccount: "Môj účet",
    currentPassword: "Aktuálne heslo",
    createPassword: "Vytvoriť heslo",
    confirmPassword: "Potvrdiť heslo",
    firstName: "Meno",
    lastName: "Priezvisko",
    changeEmail: "Zmeniť e-mail",
    changePassword: "Zmeniť heslo",
    changePhoneNumber: "Zmeniť telefónne číslo",
    deleteAccount: "Zmazať účet",
    logOut: "Odhlásiť sa",
    settings: "Nastavenia",
    saveChanges: "Uložiť zmeny",
    passDontMatch: "Heslá sa nezhodujú",
    enterPasswordCurrent: "Zadajte aktuálne heslo",
    resetPassword: "Resetovať heslo",
    backToLogin: "Späť na prihlásenie",
    historyPersonalized: "História - personalizované čítanie",
    historyFuture: "História - čítanie budúcnosti",
    historyTypePersonalized: "Personalizované čítanie",
    historyTypeFuture: "Čítanie budúcnosti",
    welcomeTo: "Vitajte v",
    tarotByAi: "Tarot od AI",
    onboardingFirstTitle: "Vitajte v",
    onboardingFirstTitleMessage: "Tarot od AI",
    onboardingSecondTitle: "Tarot od AI",
    onboardingSecondTitleMessage: "Získajte personalizované čítania",
    onboardingThirdTitle: "Tarot od AI",
    onboardingThirdTitleMessage: "Získajte čítanie o vašej budúcnosti",
    skip: "PRESKOČIŤ",
    nextOnboard: "ĎALEJ",
    clinicLoginRedirect: "Pokračovať",
  },
};
