export const langObj = {
  en: {
    login: "Login",
    email: "E-mail",
    password: "Password",
    forgotPassword: "Forgot Password",
    dntHaveAccount: "Don't have an account?",
    signUp: "Register",
    loginNow: "Login",
    alreadyAccount: "Already have an account?",
    registerLogin: "Sign in",
    register: "Register",
    currentPassword: "Current Password",
    createPassword: "New Password",
    confirmPassword: "Confirm Password",
    firstName: "First Name",
    lastName: "Last Name",
    changeEmail: "Change e-mail",
    changePassword: "Change password",
    changePhoneNumber: "Change phone number",
    deleteAccount: "Delete account",
    logOut: "Log Out",
    settings: "Settings",
    saveChanges: "Save changes",
    passDontMatch: "Passwords doesn't match",
    enterPasswordCurrent: "Enter Current Password",
  },
};
